// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamEye.Infra;

namespace TeamEye.Infra.Migrations
{
    [DbContext(typeof(TeamEyeEFContext))]
    partial class TeamEyeEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamEye.Core.Entities.Campeonato", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Ano", "Nome");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("TeamEye.Core.Entities.DetalheCampeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CampeonatoAno")
                        .HasColumnType("int");

                    b.Property<string>("CampeonatoNome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int>("GolsContra")
                        .HasColumnType("int");

                    b.Property<int>("GolsPro")
                        .HasColumnType("int");

                    b.Property<int>("Jogos")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("CampeonatoAno", "CampeonatoNome");

                    b.ToTable("DetalheCampeonatos");
                });

            modelBuilder.Entity("TeamEye.Core.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("TeamEye.Core.Entities.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeNormalizado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("TeamEye.Core.Entities.DetalheCampeonato", b =>
                {
                    b.HasOne("TeamEye.Core.Entities.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");

                    b.HasOne("TeamEye.Core.Entities.Campeonato", "Campeonato")
                        .WithMany("DetalhesCampeonato")
                        .HasForeignKey("CampeonatoAno", "CampeonatoNome");
                });

            modelBuilder.Entity("TeamEye.Core.Entities.Time", b =>
                {
                    b.HasOne("TeamEye.Core.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");
                });
#pragma warning restore 612, 618
        }
    }
}
